services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
<<<<<<< HEAD
    container_name: lgu_app_v2
    
=======
    container_name: lgu_app
>>>>>>> 6fe3e775d7907baf387ac1fad4911d33907d3705
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - lgu-network

  mysql:
    image: mysql:8.4
<<<<<<< HEAD
    container_name: lgu_mysql_v2
=======
    container_name: lgu_mysql
>>>>>>> 6fe3e775d7907baf387ac1fad4911d33907d3705
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lgu_pastpapers
      MYSQL_USER: lgu
      MYSQL_PASSWORD: lgu123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - lgu-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
<<<<<<< HEAD
    container_name: lgu_phpmyadmin_v2
=======
    container_name: lgu_phpmyadmin
>>>>>>> 6fe3e775d7907baf387ac1fad4911d33907d3705
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - lgu-network

volumes:
  mysql_data:

networks:
  lgu-network: